twig:
    default_path: '%kernel.project_dir%/templates'
    globals:
        # the value is the service's id
        principalCategories: '@App\Service\PrincipalCategories'
        arguments: '@App\Repository\CategoryRepository'
